### ISSUE TITLE
UI Theme Base (BaseDark vs BaseLight) does not apply to gathering dictionary

### ISSUE THREAD

**Issue by JasonDiBabbo** [manbeardgames/DiscerningEye#2]
The gathering dictionary, when opened with a dark theme enabled, is still showing a light theme.

Apologies if this isn't a bug, but a feature, but it came across to me as weird. I would think that as a user, if I'm specifying that I want a dark theme (i.e. dark rooms with little light), then I would be kind of thrown off when this bright screen jumps out at me.

![capture](https://cloud.githubusercontent.com/assets/1293421/13903302/14fad7a2-ee32-11e5-8964-9a2d6d0dd7eb.PNG)

**Comment by manbeardgames** [comment]
This is actually intended.  The `Flyout` control that pops out for the gathering dictionary has an `Inverse` applied to it.  It's meant to visually offset it in the foreground.  I can adjust this to be a user defined setting

**Comment by manbeardgames** [comment]
Will be added in next release

**Comment by manbeardgames** [comment]
In the newest release, there is now an option for users to choose to use the Inverse Base theme on the flyouts or not.
