### ISSUE TITLE
IMPORTANT: 3.4 new nodes

### ISSUE THREAD

**Issue by killaman777** [manbeardgames/DiscerningEye#21]
Star Cotton boll 12PM |Slot 4| Azys Lia| Abalathian Botanist book
Brown Mushroom 4PM| Slot 7| Zenith| Dravanian Botanist Folklore 
Teak log 6PM |Slot 6| Dravanian Hinterlands| Dravanian Botanist folklore
Noble Sage 8PM | Slot 1| Dravanian Forelands| Dravanian Botanist Folklore
Luminium Ore 4AM| Slot 6| Azys Lia | Abalatian mining Folklore
Zeolite Ore 6AM | Slot 4| Dravanian Hinterlands| Dravanian mining Folklore
Tungstite 8AM| Slot 4| Coerthas Western| Coerthas mining Folklore

**Comment by manbeardgames** [comment]
Hey, sorry haven't added these yet, i'll be putting them in this afternoon/tonight

**Comment by manbeardgames** [comment]
Items have been added (reference [https://github.com/dartvalince/DiscerningEye-Alarms/releases/tag/10032016](https://github.com/dartvalince/DiscerningEye-Alarms/releases/tag/10032016))

The next time you open the app, the alarm file should automatically download and you'll see the new added items in the alarm lists
