### ISSUE TITLE
Missing folklore nodes.

### ISSUE THREAD

**Issue by killaman777** [manbeardgames/DiscerningEye#6]
1PM-2PM Frost Cotton Boll   slot 4  Coerthas Western Highlands  (x36.7,y13.0,z1.3)  
Used to make Eikon Cloth

3PM-4PM Old-growth Camphorwood Log  Slot 6  The Churning Mists  (x11.6,y10.6,z3.3)  
Used to make Treated Camphorwood Lumber

1AM-2AM Smithsonite Ore slot 2  The Sea of Clouds   (x38.1,y14.8,z2.2)  
Used to make Eikon Iron Ingot

3AM-4AM Lumythrite Ore  slot 2  The Churning Mists  (x6.2,y20.3,z3.4)  
Used to make High Mythrite Ingot

**Comment by manbeardgames** [comment]
Adding these to the data file.  Next update will include an auto updater that will pull the most recent version of the alarm data when a user opens.  These will be added in during that update

**Comment by manbeardgames** [comment]
Thanks for the information, these have been added in the newest release.
