### ISSUE TITLE
Gathering Dictionary - Star Rating

### ISSUE THREAD

**Issue by Dolmaz** [manbeardgames/DiscerningEye#8]
When going to the gathering dictionary and looking at star rated items, it gives `&#9733;` for the star instead of the actual glyph.

**Comment by manbeardgames** [comment]
Fixed in current commit.  Will be available in next update.

![Image of fix](http://i.imgur.com/7Z5udPH.png)

**Comment by manbeardgames** [comment]
This was fixed in the latest release.  If you have at minimum the 0.1.2.12 version of the application, it will automatically update to the new release for you next time you open the app. 

Reference: https://github.com/dartvalince/DiscerningEye/releases/tag/0.1.2.15
