### ISSUE TITLE
Old-growth Camphorwood Log alarm set to wrong time

### ISSUE THREAD

**Issue by paratgh** [manbeardgames/DiscerningEye#9]
Is 3am-4am, should be 3pm-4pm.

**Comment by manbeardgames** [comment]
Thanks, I'll get this changed and fixed tomorrow afternoon. I apologize abut the mixup there.  The alarm data file will update itself automatically when I adjust it, so no need to re download anything on your end.  I'll comment back here when I've pushed the change

**Comment by manbeardgames** [comment]
Alarm file has been updated. Next time you open the app, the new alarm data will automatically download for you.  

Reference: https://github.com/dartvalince/DiscerningEye-Alarms/releases/tag/04012016
